### ISSUE TITLE
Update ST3 sidebar icons color

### ISSUE THREAD

**Issue by billmn** [daylerees/colour-schemes#158]
The new update of Sublime Text 3 introduce sidebar icons and now some themes require colors adjustment.

In my case with Juicy Theme:  

![schermata 2014-08-29 alle 08 47 53](https://cloud.githubusercontent.com/assets/779534/4087167/854aba2c-2f48-11e4-92d0-23b275e73f4f.png)

**Comment by yanickrochon** [comment]
My side bar is not affected by any theme... how do you apply the theme? (Build 3103)

**Comment by billmn** [comment]
This is an old issue (2014).
Solved
