### ISSUE TITLE
Sublime 3 corrupted icons

### ISSUE THREAD

**Issue by aenciso** [daylerees/colour-schemes#175]
Hi,

I've just installed peacock theme on Sublime 3 Build 3083 and all icons got corrupted ('x' and arrows) as shown below.

![image](https://cloud.githubusercontent.com/assets/3810819/7178706/cac18fdc-e428-11e4-906d-3c46b11b3e57.png)

I've tried changing to different themes and still have the same issue. I've also noticed that if I remove the line 

"theme" : "peacock.sublime-theme",

from my user config all icons show correctly.

**Comment by andytruett** [comment]
@aenciso Do you have [Space Gray](http://kkga.github.io/spacegray/) installed?

From the readme:

>The Sublime UI themes are based on [Space Gray](http://kkga.github.io/spacegray/) by [kkga_](http://twitter.com/kkga_).
>
>The above theme MUST be installed before enabling my UI themes, since it uses its assets. You must also install this colour schemes package as per usual.

**Comment by aenciso** [comment]
Yes I had it installed. I ended up installing Seti and that fixed the issue.
I´m using zacks-contrast theme with Seti.

Thanks
