### ISSUE TITLE
Support for WebStorm?

### ISSUE THREAD

**Issue by mato75** [daylerees/colour-schemes#177]
Is it possible to create colour schemes for webstorm.

**Comment by Anahkiasen** [comment]
We already have those no? https://github.com/daylerees/colour-schemes/tree/master/jetbrains

**Comment by mato75** [comment]
but how can you import icls info webstorm?

**Comment by SimonErich** [comment]
@mato75 just download the files and put them in your Webstom perferences folder (Linux: ~/.WebStorm10/config/colors/) folder.
Then go to File > Settings -> Colors & Fonts and choose your theme.

**Comment by mato75** [comment]
thx, will try.
