### ISSUE TITLE
Weird UI icons in Sublime Text 3

### ISSUE THREAD

**Issue by jankazemier** [daylerees/colour-schemes#178]
When setting the theme to anything in this pack, my icons become a weird orange and green-ish square in stead of fold-icons and close-icon:

![st3-icons](https://cloud.githubusercontent.com/assets/355155/7856033/433edcda-0526-11e5-9104-f4339a62fd0d.png)

Running Windows 7 64-bit, ST3 build 3083 (stable)

**Comment by ksnyde** [comment]
That looks like a default behaviour of the Sublime Linter, I have seen the same when using non-daylerees schemes. I'm not an expert on these matters but I suspect that you'd be better off looking at the linting configuration you have setup for JSON files.

**Comment by jankazemier** [comment]
I have removed ST3 from my computer, removed my "%APPDATA%\Roaming\Sublime Text 3" folder, reinstalled ST3, then only installed Dayle Rees Color Schemes an only set the theme to juicy in Settings - User (i.e. no other settings were set). The same problem still persists.

**Comment by jankazemier** [comment]
Apparently Package Control does not leave the extracted files, so installing manually is a workaround.

So that changes this issue to a request:
In order to be compatible with Package Control 2.0, please add an empty file called ```.no-sublime-package``` to the root of the package.

Also see: https://github.com/wbond/package_control/issues/349

**Comment by jankazemier** [comment]
My bad.
