### ISSUE TITLE
Themes look different than demo in PhpStorm 2016.1.2

### ISSUE THREAD

**Issue by alimfazeli** [daylerees/colour-schemes#203]
For example this is how mellow contrast is supposed to look: 
![screenshot from 2016-07-05 10-50-14](https://cloud.githubusercontent.com/assets/12569051/16575630/0761b680-429f-11e6-8e6c-e80ddc712d25.png)

This is how it looks on my Jetbrains Phpstorm:
![screenshot from 2016-07-05 10-51-33](https://cloud.githubusercontent.com/assets/12569051/16575629/075c6f22-429f-11e6-9e16-b2b7cf728d2a.png)

Why does this happen?
Does anyone know a solution to the problem i have?

**Comment by noplanman** [comment]
I'm having the same issue with Earthsong, but it probably affects all themes.
Maybe some keywords changed in the new versions of PhpStorm 😕

**Comment by rsteinmann** [comment]
Same Problem for me with Peacock, Mud, Keen ... tried couple of schemes but they all seem bugged. I use the 2016.2 Release of PHPStorm on Mac.

**Comment by daylerees** [comment]
Hi guys. I get this a lot (and need to find a better way to communicate it). The theme examples are from Sublime, which has a completely different theme rendering system. It can do things PHP storm can't (like have function and scope a different colour).

I haven't managed to improve the mapping for all themes yet, but if you try my other repo : https://github.com/daylerees/material-peacock - then I think you'll have better results.

Sorry about that!

**Comment by noplanman** [comment]
> I get this a lot (and need to find a better way to communicate it).
I'd suggest to just write this somewhere. In the readme or demo page I couldn't find anything mentioning this.
It might also be an idea to add a paragraph at the top of the demo page that explains "The following screenshots are made for Sublime, other editors may look different."

Thanks for all the grunt work by the way, must be insane.

**Comment by Anahkiasen** [comment]
It is in the README, it says the IntellijIDEA products are supported at 60% https://github.com/daylerees/colour-schemes#compatibility

**Comment by noplanman** [comment]
Yes I saw that, but what does that actually mean?
That 60% of the theme colours work or that 60% of the themes themselves work or that 60% of the themes are fully compatible?

(I know I'm being a bit of a devil's advocate here)

I just think it would make sense to make a more tangible statement somewhere, which everybody can easily understand, because just stating the % of compatibility clearly isn't working.
Doesn't this make sense?
