### ISSUE TITLE
theme for vscode

### ISSUE THREAD

**Issue by MandarSant** [daylerees/colour-schemes#212]
support for vscode

**Comment by danvirsen** [comment]
I forked the repository and added patterns to generate vscode themes based on the textmate patterns. I think it looks good, but feel free to check it out and and see if anything needs tweaking.
If it looks good I can create a pull request for it.

https://github.com/danvirsen/colour-schemes

**Comment by MandarSant** [comment]
@danvirsen  how to add to` vscode`

**Comment by danvirsen** [comment]
If that was a question, I added installation instructions to the readme. :)

Just copy the theme folder that you want from the `vscode` folder in the repository into `~/.vscode/extensions` (mac/linux) or `%USERPROFILE%\.vscode\extensions` (windows).
